[supervisord]
nodaemon=true
user=root

[program:app-service]
command=python /app/app.py
autostart=true
autorestart=true
stdout_logfile=/var/log/app.log
priority=10
stderr_logfile=/var/log/app_error.log

[program:bot-service]
command=python /app/bot.py
autostart=true
autorestart=true
stdout_logfile=/var/log/bot.log
priority=20
stderr_logfile=/var/log/bot_error.log
